### ISSUE TITLE
Custom user properties for cell

### ISSUE THREAD

**Issue by titan83** [Alexander-r/QtXlsxWriter#1]
Hello, I see that you are doing great job (90 commits ahead from original), that's fantastic.
I just begin to use this library and I have a question: is it possible to add some user's defined properties to cells?
I see *property functions in xlsxformat class, but they mark as "internal".
Or I need to create my own inherit class for implementing this feature?
Thanks.

**Comment by Alexander-r** [comment]
So far all the commits are just a combination of all the changes from all the other forks of original project and a couple of small fixes.
To be honest I don't know much about the file format so I'm not sure I can help with new features. The best I can do is provide bug fixes to existing functionality.

As for your question, all the property functions in xlsxformat are internal because they just set the format flags which are later handled elsewhere. Adding new property there will not actually add it to the resulting file. Most of the properties that deal with styles are for example handled in xlsxstyles based on which of the properties from FormatPrivate were set. They are just added as corresponding attribute to resulting xml file (see places where actual writer.writeAttribute is done). So if you want to add more properties like that that's the place to start.

In the xlsx format specification I see custom file properties (and they are handled in xlsxdocument). But I don't see anything for cells. Maybe I can help more if you provide a document with an example of custom properties you are trying to add.

**Comment by titan83** [comment]
Thanks for your answer.
I will think about optimal solution for me.

**Comment by Alexander-r** [comment]
I will close this issue since there are no updates.
Feel free to reopen it or open a new one if you have further updates.
